"""empty message

Revision ID: 2a1459a7e4d0
Revises: 4a4cca10d9f4
Create Date: 2020-09-29 22:08:13.540595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1459a7e4d0'
down_revision = '4a4cca10d9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
